config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :lists

end

app/models/list.rb
class List < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  class << self
    def from_omniauth(auth_hash)
      user = find_or_create_by(uid: auth_hash['uid'], provider: auth_hash['provider'])
      user.name = auth_hash['info']['name']
      user.location = auth_hash['info']['location']
      user.image_url = auth_hash['info']['image']
      user.url = auth_hash['info']['urls']['Twitter']
      user.token = auth_hash['credentials']['token']
      user.secret = auth_hash['credentials']['secret']
      user.save!
      user
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  helper_method :current_user
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_action :init_twitter, except: [:index]

    def index
    end

    def new
    end

    def create
      begin
        username = params[:username]
        list = @client.create_list(username, options = {mode: "private", description: "List created using FreshPerspective"})
        friends = @client.friend_ids(username, options = {cursor:-1, count: 500})
        friends.each_slice(100) do |slice|
          @client.add_list_members(list.id, slice)
        end
        redirect_to list.uri.to_s
      rescue Twitter::Error => e
        flash[:danger] = "#{e.message}"
        redirect_to new_list_path
      end
    end

    private

    def init_twitter
      @client = Twitter::REST::Client.new do |config|
        config.consumer_key        = ENV['TWITTER_KEY']
        config.consumer_secret     = ENV['TWITTER_SECRET']
        config.access_token        = current_user.token
        config.access_token_secret = current_user.secret
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    begin
      @user = User.from_omniauth(request.env['omniauth.auth'])
      session[:user_id] = @user.id
      redirect_to new_list_path
    rescue
      flash[:warning] = "There was an error while trying to authenticate you..."
      redirect_to root_path
    end

  end

  def destroy
    if current_user
      session.delete(:user_id)
      flash[:success] = "Thanks for trying out FreshPerspective!"
    end
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_alerts.html.erb
<div class="row">
  <div class="col-md-8">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">FreshPerspective</a>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FreshPerspective</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- start Mixpanel --><script type="text/javascript">(function(e,a){if(!a.__SV){var b=window;try{var c,l,i,j=b.location,g=j.hash;c=function(a,b){return(l=a.match(RegExp(b+"=([^&]*)")))?l[1]:null};g&&c(g,"state")&&(i=JSON.parse(decodeURIComponent(c(g,"state"))),"mpeditor"===i.action&&(b.sessionStorage.setItem("_mpcehash",g),history.replaceState(i.desiredHash||"",e.title,j.pathname+j.search)))}catch(m){}var k,h;window.mixpanel=a;a._i=[];a.init=function(b,c,f){function e(b,a){var c=a.split(".");2==c.length&&(b=b[c[0]],a=c[1]);b[a]=function(){b.push([a].concat(Array.prototype.slice.call(arguments,
  0)))}}var d=a;"undefined"!==typeof f?d=a[f]=[]:f="mixpanel";d.people=d.people||[];d.toString=function(b){var a="mixpanel";"mixpanel"!==f&&(a+="."+f);b||(a+=" (stub)");return a};d.people.toString=function(){return d.toString(1)+".people (stub)"};k="disable time_event track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config reset people.set people.set_once people.increment people.append people.union people.track_charge people.clear_charges people.delete_user".split(" ");
  for(h=0;h<k.length;h++)e(d,k[h]);a._i.push([b,c,f])};a.__SV=1.2;b=e.createElement("script");b.type="text/javascript";b.async=!0;b.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?MIXPANEL_CUSTOM_LIB_URL:"file:"===e.location.protocol&&"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^\/\//)?"https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js":"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";c=e.getElementsByTagName("script")[0];c.parentNode.insertBefore(b,c)}})(document,window.mixpanel||[]);
  mixpanel.init("e2362fa3124edbac946f980c586f414e");</script><!-- end Mixpanel -->
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= render 'layouts/alerts'%>
    <%= yield %>
  </div>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/lists/_recommendations.html.erb
<div class="recommended-profiles">
  <%= button_to lists_path(:username=>"zellie"), method: :create, class: "btn btn-default profile-card" do%>
  <%= image_tag "zellie.jpeg", class:"profile-pic" %>
  <p class="profile-name">Zellie Imani</p>
  <p class="profile-description">All Black Everything. Teacher. Blogger. Activist. Brother. Son.</p>
  <% end %>

  <%= button_to lists_path(:username=>"LibyaLiberty"), method: :create, class: "btn btn-default profile-card" do%>
  <%= image_tag "hend.jpeg",class:"profile-pic" %>
  <p class="profile-name">Hend Amry</p>
  <p class="profile-description">I am East and West, citizen and refugee. The melting pot is a failed paradigm-maybe more like a tossed salad. I am an international crouton.</p>
  <% end %>

  <%= button_to lists_path(:username=>"noahpinion"), method: :create, class: "btn btn-default profile-card" do%>
  <%= image_tag "noah.jpeg", class:"profile-pic" %>
  <p class="profile-name">Noah Smith</p>
  <p class="profile-description">Dual-class Human Economist/Bloomberg View writer</p>
  <% end %>

  <%= button_to lists_path(:username=>"ErinEhyde200"), method: :create, class: "btn btn-default profile-card" do%>
  <%= image_tag "erin.jpeg", class:"profile-pic" %>
  <p class="profile-name">Erin Ehyde</p>
  <p class="profile-description">Happily Married, mother of three amazing kids. Blessed with a wonderful life. Obsessed with politics, love my country, constitution and my fellow man!</p>
  <% end %>
</div>

app/views/lists/index.html.erb
<div class="row">
  <div class="col-md-8">
    <p class="lead">See Twitter from someone else's perspective. FreshPerspective creates a Twitter list with the accounts someone else follows.</p>
    <%= link_to "#{image_tag('twitter_logo.svg', size:'24')}".html_safe + " Sign in with Twitter", '/auth/twitter', class: 'btn btn-default btn-mobile btn-outline', id: 'twitter-btn' %>
    <br/>
    <br/>
    <p class="small">Note: Twitter is strict about how many lists you can create and how many users you can follow. If you get an error, you might have to try again later</p>
  </div>
</div>

<script type="text/javascript">
mixpanel.track_links("#twitter-btn", "click twitter auth", {
  "referrer": document.referrer
});
</script>

app/views/lists/new.html.erb
<div class="row">
  <div class="col-md-8">
    <%= render 'shared/loading' %>
    <div class="new-list">
    <p class="lead">Type the Twitter username of the person whose timeline you’d like to read</p>
    <%= form_tag('/lists', method: :post, class:"form", id:'create-list') do %>
    <div class="form-group">
      <%= text_field_tag 'username', "", class: "form-control input-mobile", id: "username"%>
    </div>
    <%= submit_tag 'Create List', class: "btn btn-default btn-mobile btn-outline" %>
    <% end %>
    <br/>
    <p class="small">Note: Twitter is strict about how many lists you can create and how many users you can follow. If you get an error, you might have to try again later</p>
    <%= link_to 'Sign in with another account', logout_path, method: :delete, class:"small" %>
    </div>
  </div>
</div>

app/views/shared/_loading.html.erb
<span id="loading"> <p class="lead">Creating your Twitter list...</p>
  <div class="progress">
    <div class="progress-bar progress-bar-info progress-bar-striped active" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width:100%">
    </div>
  </div>
</span>